{
 wikimedia_connection_library_cache: '/media/mateusz/OSM_cache',
 downloaded_osm_file_storage_location: '/media/mateusz/OSM_cache/cache-for-wikipedia-validator',
 database_filepath: '/media/mateusz/OSM_cache/cache-for-wikipedia-validator/database.db',
 validator_report_repository_location: '/media/mateusz/OSM_cache/OSM-wikipedia-tag-validator-reports'
}
